version: '3'

services:
  go:
    container_name: snippetbox-go
    build:
      context: .
      dockerfile: go.dockerfile
      args:
        - GITHUB_USER_NAME=$GITHUB_USER_NAME
    tty: true
    volumes:
      - ./code:/go/src/github.com/$GITHUB_USER_NAME
    ports:
      - 4000:4000

  mysql:
    container_name: snippetbox-mysql
    build:
      context: .
      dockerfile: mysql.dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
