settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: snippetbox
  path: .
  commands:
    install:
      status: true
      method: go build -o snippetbox ./cmd/web/
    run:
      status: true
      method: ./snippetbox
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
